storage_cfg:                                      
  controllers:                                    
    - deviceSlot: "Embedded"                      
      importConfiguration: false                  
      initialize: true                            
      mode: "RAID"                                
      logicalDrives:
      - bootable: true
        driveTechnology: null
        name: "os"
        numPhysicalDrives: 2
        raidLevel: "RAID1"
        sasLogicalJBODId: null


bios_settings:                                    
- id: "CustomPostMessage"                         
  value: "!! automate the planet !!"              
- id: "MinProcIdlePkgState"                       
  value: "NoState"                                
- id: "EnergyPerfBias"                            
  value: "MaxPerf"                                
- id: "PowerProfile"                              
  value: "MaxPerf"                                
- id: "IntelQpiPowerManagement"                   
  value: "Disabled"                               
- id: "PowerRegulator"                            
  value: "StaticHighPerf"                         
- id: "MinProcIdlePower"                          
  value: "NoCStates"                              
